[2023-09-04T02:54:03.914+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=dag_with_postgres_operator_v02/run_id=scheduled__2023-09-02T00:00:00+00:00/task_id=insert_into_table permission to 509
[2023-09-04T02:54:03.915+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=dag_with_postgres_operator_v02/run_id=scheduled__2023-09-02T00:00:00+00:00/task_id=insert_into_table permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=dag_with_postgres_operator_v02/run_id=scheduled__2023-09-02T00:00:00+00:00/task_id=insert_into_table'
[2023-09-04T02:54:03.951+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=dag_with_postgres_operator_v02/run_id=scheduled__2023-09-02T00:00:00+00:00/task_id=insert_into_table permission to 509
[2023-09-04T02:54:03.953+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=dag_with_postgres_operator_v02/run_id=scheduled__2023-09-02T00:00:00+00:00/task_id=insert_into_table permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=dag_with_postgres_operator_v02/run_id=scheduled__2023-09-02T00:00:00+00:00/task_id=insert_into_table'
[2023-09-04T02:54:03.989+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v02.insert_into_table scheduled__2023-09-02T00:00:00+00:00 [queued]>
[2023-09-04T02:54:04.003+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v02.insert_into_table scheduled__2023-09-02T00:00:00+00:00 [queued]>
[2023-09-04T02:54:04.004+0000] {taskinstance.py:1361} INFO - Starting attempt 6 of 6
[2023-09-04T02:54:04.022+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): insert_into_table> on 2023-09-02 00:00:00+00:00
[2023-09-04T02:54:04.077+0000] {standard_task_runner.py:57} INFO - Started process 503 to run task
[2023-09-04T02:54:04.079+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v02', 'insert_into_table', 'scheduled__2023-09-02T00:00:00+00:00', '--job-id', '81', '--raw', '--subdir', 'DAGS_FOLDER/dag-postgres-operator.py', '--cfg-path', '/tmp/tmpb7toar27']
[2023-09-04T02:54:04.082+0000] {standard_task_runner.py:85} INFO - Job 81: Subtask insert_into_table
[2023-09-04T02:54:04.147+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=dag_with_postgres_operator_v02/run_id=scheduled__2023-09-02T00:00:00+00:00/task_id=insert_into_table permission to 509
[2023-09-04T02:54:04.147+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=dag_with_postgres_operator_v02/run_id=scheduled__2023-09-02T00:00:00+00:00/task_id=insert_into_table permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=dag_with_postgres_operator_v02/run_id=scheduled__2023-09-02T00:00:00+00:00/task_id=insert_into_table'
[2023-09-04T02:54:04.150+0000] {task_command.py:415} INFO - Running <TaskInstance: dag_with_postgres_operator_v02.insert_into_table scheduled__2023-09-02T00:00:00+00:00 [running]> on host 6c82fec646db
[2023-09-04T02:54:04.256+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='qpsss' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator_v02' AIRFLOW_CTX_TASK_ID='insert_into_table' AIRFLOW_CTX_EXECUTION_DATE='2023-09-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='6' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-02T00:00:00+00:00'
[2023-09-04T02:54:04.259+0000] {sql.py:274} INFO - Executing: 
            insert into dag_runs (dt, dag_id) values ('2023-09-02', 'dag_with_postgres_operator_v02')
        
[2023-09-04T02:54:04.270+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-09-04T02:54:04.281+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-09-04T02:54:04.286+0000] {sql.py:418} INFO - Running statement: 
            insert into dag_runs (dt, dag_id) values ('2023-09-02', 'dag_with_postgres_operator_v02')
        , parameters: None
[2023-09-04T02:54:04.289+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 280, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 392, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 423, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "dag_runs_pkey"
DETAIL:  Key (dt, dag_id)=(2023-09-02, dag_with_postgres_operator_v02) already exists.

[2023-09-04T02:54:04.301+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=dag_with_postgres_operator_v02, task_id=insert_into_table, execution_date=20230902T000000, start_date=20230904T025403, end_date=20230904T025404
[2023-09-04T02:54:04.320+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 81 for task insert_into_table (duplicate key value violates unique constraint "dag_runs_pkey"
DETAIL:  Key (dt, dag_id)=(2023-09-02, dag_with_postgres_operator_v02) already exists.
; 503)
[2023-09-04T02:54:04.335+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-04T02:54:04.356+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
