[2023-09-02T08:29:17.713+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=dag_with_postgres_operator_v01/run_id=manual__2023-09-02T08:29:16.405187+00:00/task_id=create_postgres_table permission to 509
[2023-09-02T08:29:17.714+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=dag_with_postgres_operator_v01/run_id=manual__2023-09-02T08:29:16.405187+00:00/task_id=create_postgres_table permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=dag_with_postgres_operator_v01/run_id=manual__2023-09-02T08:29:16.405187+00:00/task_id=create_postgres_table'
[2023-09-02T08:29:17.744+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=dag_with_postgres_operator_v01/run_id=manual__2023-09-02T08:29:16.405187+00:00/task_id=create_postgres_table permission to 509
[2023-09-02T08:29:17.745+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=dag_with_postgres_operator_v01/run_id=manual__2023-09-02T08:29:16.405187+00:00/task_id=create_postgres_table permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=dag_with_postgres_operator_v01/run_id=manual__2023-09-02T08:29:16.405187+00:00/task_id=create_postgres_table'
[2023-09-02T08:29:17.785+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v01.create_postgres_table manual__2023-09-02T08:29:16.405187+00:00 [queued]>
[2023-09-02T08:29:17.797+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v01.create_postgres_table manual__2023-09-02T08:29:16.405187+00:00 [queued]>
[2023-09-02T08:29:17.798+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 6
[2023-09-02T08:29:17.817+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): create_postgres_table> on 2023-09-02 08:29:16.405187+00:00
[2023-09-02T08:29:17.825+0000] {standard_task_runner.py:57} INFO - Started process 962 to run task
[2023-09-02T08:29:17.828+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v01', 'create_postgres_table', 'manual__2023-09-02T08:29:16.405187+00:00', '--job-id', '47', '--raw', '--subdir', 'DAGS_FOLDER/dag-postgres-operator.py', '--cfg-path', '/tmp/tmp4nfzwyis']
[2023-09-02T08:29:17.832+0000] {standard_task_runner.py:85} INFO - Job 47: Subtask create_postgres_table
[2023-09-02T08:29:17.889+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=dag_with_postgres_operator_v01/run_id=manual__2023-09-02T08:29:16.405187+00:00/task_id=create_postgres_table permission to 509
[2023-09-02T08:29:17.890+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=dag_with_postgres_operator_v01/run_id=manual__2023-09-02T08:29:16.405187+00:00/task_id=create_postgres_table permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=dag_with_postgres_operator_v01/run_id=manual__2023-09-02T08:29:16.405187+00:00/task_id=create_postgres_table'
[2023-09-02T08:29:17.893+0000] {task_command.py:415} INFO - Running <TaskInstance: dag_with_postgres_operator_v01.create_postgres_table manual__2023-09-02T08:29:16.405187+00:00 [running]> on host 6c82fec646db
[2023-09-02T08:29:17.982+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='qpsss' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator_v01' AIRFLOW_CTX_TASK_ID='create_postgres_table' AIRFLOW_CTX_EXECUTION_DATE='2023-09-02T08:29:16.405187+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-02T08:29:16.405187+00:00'
[2023-09-02T08:29:17.984+0000] {sql.py:274} INFO - Executing: 
            create table if not exist dag_runs (
                dt date,
                dag_id character varying,
                primary key (dt, datg_ig)
            )
        
[2023-09-02T08:29:18.003+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 275, in execute
    hook = self.get_db_hook()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 186, in get_db_hook
    return self._hook
  File "/usr/local/lib/python3.8/functools.py", line 967, in __get__
    val = self.func(instance)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 148, in _hook
    conn = BaseHook.get_connection(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/connection.py", line 477, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_localhost` isn't defined
[2023-09-02T08:29:18.009+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_postgres_operator_v01, task_id=create_postgres_table, execution_date=20230902T082916, start_date=20230902T082917, end_date=20230902T082918
[2023-09-02T08:29:18.026+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 47 for task create_postgres_table (The conn_id `postgres_localhost` isn't defined; 962)
[2023-09-02T08:29:18.044+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-02T08:29:18.065+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
